spec/features/conditions/user_sees_conditions_index_page_spec.rb, spec/features/stations/user_sees_index_page_spec.rb
first couple of tests. stations index and conditions index
=> Andrew station

.gitignore, spec/features/visitor_sees_station_show_spec.rb, spec/features/visitor_sees_trip_show_spec.rb
Adds visitor station show spec
Adds visitor trip show spec
=> Adds 2 feature tests

spec/features/authenticate_new_user_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #7
Link:  https://media.giphy.com/media/zaezT79s3Ng7C/giphy.gif
=> adds user registration spec

spec/features/accessories/user_sees_bike_shop_spec.rb
__x_ Wrote Tests
____ Reviewed
- [] Bug Fix
* write tests for the bike shop
closes #
Link:  https://media.giphy.com/media/l3V0p1BV7BUlppblm/giphy.gif
=> Bike shop tests

spec/features/authenticate_registered_user_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
Link: https://tenor.com/wFCi.gif
=> adds authenticate registered user spec

spec/features/conditions/condition_show_spec.rb, spec/features/trips/trip_index_spec.rb, spec/features/users/user_authorization_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
Link: ![Alt Text](https://media.giphy.com/media/10ZEx0FoCU2XVm/giphy.gif)
=> add user authorization feature spec

spec/features/accessories/user_sees_accessory_show_page_spec.rb, spec/features/accessories/user_sees_cart_page_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
Link: ![Alt Text](https://media.giphy.com/media/gw3IWyGkC0rsazTi/giphy.gif)
=> Accessory show spec

app/models/accessory.rb, app/models/condition.rb, app/models/station.rb, app/models/trip.rb, app/models/user.rb, db/migrate/20180908215115_create_stations.rb, db/migrate/20180908215501_create_conditions.rb, db/migrate/20180908215628_create_users.rb, db/migrate/20180908220250_create_trips.rb, db/migrate/20180908220427_create_accessories.rb, db/schema.rb, spec/factories/accessories.rb, spec/factories/conditions.rb, spec/factories/stations.rb, spec/factories/trips.rb, spec/factories/users.rb, spec/models/accessory_spec.rb, spec/models/condition_spec.rb, spec/models/station_spec.rb, spec/models/trip_spec.rb, spec/models/user_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
- [x I have reviewed my code
=> adds initial tables

Gemfile, Gemfile.lock, app/models/user.rb, spec/factories/accessories.rb, spec/factories/conditions.rb, spec/factories/stations.rb, spec/factories/trips.rb, spec/factories/users.rb, spec/features/visitor_adds_to_cart_spec.rb, spec/features/visitor_removes_from_cart_spec.rb
____ Reviewed
* description
closes #
=> adds faker, fixes gemfile, changes some tests

app/assets/javascripts/stations.coffee, app/assets/stylesheets/stations.scss, app/controllers/stations_controller.rb, app/helpers/stations_helper.rb, app/models/station.rb, app/views/stations/index.html.erb, config/routes.rb, spec/controllers/stations_controller_spec.rb, spec/features/stations/user_sees_index_page_spec.rb
__x_ Wrote Tests
__x_ Reviewed
- x] All Tests are Passing
- [] Bug Fix
* user story 1 done
closes #
=> user story 1

app/controllers/trips_controller.rb, app/models/trip.rb, app/views/trips/show.html.erb, spec/features/trips/visitor_sees_trip_show_spec.rb
__x_ Wrote Tests
____ Reviewed
- [] Bug Fix
*  implements 
closes #
=> user story 4

Gemfile, Gemfile.lock, app/controllers/stations_controller.rb, app/models/station.rb, app/views/stations/show.html.erb, config/initializers/friendly_id.rb, config/routes.rb, db/migrate/20180909182610_create_friendly_id_slugs.rb, db/migrate/20180909183432_add_slug_to_stations.rb, db/schema.rb, spec/features/stations/visitor_sees_station_show_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #2 
=> Station show route/controller/view, adds slug implementation

Gemfile, Gemfile.lock, app/controllers/trips_controller.rb, app/models/station.rb, app/views/trips/index.html.erb, config/routes.rb, spec/features/trips/trip_index_spec.rb
____ Reviewed
- [] Bug Fix
* description: Adds pagination gem, updates trips index to include page links, updates trips index spec
closes #3 
=> Pagination

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, config/routes.rb, spec/features/users/authenticate_new_user_spec.rb, spec/features/users/authenticate_registered_user_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #7 #16 
=> New user reg

app/controllers/sessions_controller.rb, spec/features/stations/visitor_sees_station_show_spec.rb, spec/features/users/authenticate_registered_user_spec.rb
____ Reviewed
* description
closes #
=> adds logout functionality

app/controllers/application_controller.rb, app/controllers/carts_controller.rb, app/models/cart.rb, app/views/accessories/index.html.erb, app/views/layouts/application.html.erb, spec/features/cart/visitor_adds_to_cart_spec.rb, spec/features/stations/visitor_sees_station_show_spec.rb, spec/models/cart_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
=> Cart feature

app/controllers/users_controller.rb, spec/features/users/user_authorization_spec.rb
____ Reviewed
* description: Fixes user authorization - no longer allows a user to alter the uri to see another user's account info
closes #15  
closes #20 
=> add a fix to user authorization

app/controllers/orders_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/accessory.rb, app/models/order.rb, app/models/order_accessory.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/orders/show.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20180911192320_create_orders.rb, db/migrate/20180911193034_create_order_accessories.rb, db/migrate/20180911200015_add_quantity_and_unit_price_to_order_accessories.rb, db/migrate/20180911200926_change_status_column_orders.rb, db/schema.rb, spec/factories/users.rb, spec/features/users/authenticate_registered_user_spec.rb, spec/features/users/user_authorization_spec.rb, spec/features/users/user_sees_their_dashboard_spec.rb, spec/models/accessory_spec.rb, spec/models/order_accessory_spec.rb, spec/models/order_spec.rb, spec/models/user_spec.rb
x Wrote Tests
x Implemented
____ Reviewed
- [] Bug Fix
* description
* Adds user dashboard path dashboard_path
* Adds ability for user to visit their dashboard and see their orders
* Adds order show page for user order
* Adds Orders table
* Adds OrderAccessories table
* Sets up relationships between Users, Orders, and OrderAccessories tables
closes #19 
https://media.giphy.com/media/l6G8YjNTw6ODm/giphy.gif
=> User dashboard

app/controllers/carts_controller.rb, app/models/cart.rb, app/views/carts/index.html.erb, config/routes.rb, spec/features/cart/visitor_adds_to_cart_spec.rb, spec/models/cart_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #9 
=> Cart page build

spec/features/accessories/user_sees_accessory_show_page_spec.rb, spec/features/admin/stations/admin_stations_index_spec.rb
____ Reviewed
* description
closes #
=> Test fixes aq

app/controllers/carts_controller.rb, app/views/carts/index.html.erb, app/views/layouts/application.html.erb, spec/features/cart/user_sees_cart_page_spec.rb, spec/features/cart/visitor_removes_from_cart_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
=> Cart things

app/controllers/admin/stations_controller.rb, app/views/admin/stations/index.html.erb, app/views/admin/stations/show.html.erb, app/views/trips/index.html.erb, config/routes.rb, spec/features/admin/stations/admin_station_show_spec.rb, spec/features/admin/stations/admin_stations_index_spec.rb
_x___ Implemented
____ Reviewed
- [] Bug Fix
* description Add User Story 29 - Admin sees station show page: station attributes plus edit and delete links/buttons
closes #29
=> add admin station show feature and spec, user story 29

db/seeds.rb
____ Reviewed
- [] Bug Fix
* description
* Adjusts seed code for conditions table to grab CSV more randomly
closes #
https://media.giphy.com/media/VOjfWZnMNeNXi/giphy.gif
=> Fixes seed for trips table, now with more random seeding

app/controllers/carts_controller.rb, app/controllers/sessions_controller.rb, app/views/layouts/application.html.erb, spec/features/admin/stations/admin_station_show_spec.rb, spec/features/cart/user_sees_cart_page_spec.rb, spec/features/users/authenticate_registered_user_spec.rb
____ Reviewed
adds checkout functionality for visitor and user, adds login flash for incorrect credentials
closes #
=> Checkout and Login Functionality

app/models/station.rb, app/views/stations/show.html.erb, spec/features/admin/stations/admin_station_show_spec.rb, spec/features/stations/user_sees_station_show_page_spec.rb, spec/models/station_spec.rb
x Wrote Tests
x Implemented
____ Reviewed
- [] Bug Fix
* description
* Adds Station show page dashboard for registered users
* Adds the following instance methods to Station model:
* #number_rides_started
* #number_rides_ended
* #most_frequent_destination
* #most_frequent_origination
* #date_for_most_trips_started
* #top_starting_user_zipcode
* #top_starting_bike_id
closes #23 
https://media.giphy.com/media/JV2RNo8dKV1TO/giphy.gif
=> Add Station show page dashboard for registered users

app/controllers/admin/base_controller.rb, app/controllers/admin/dashboard_controller.rb, app/controllers/admin/stations_controller.rb, app/models/station.rb, app/views/admin/base/dashboard.html.erb, app/views/admin/stations/index.html.erb, app/views/admin/stations/new.html.erb, pull_request_template.md, spec/features/admin/stations/admin_station_show_spec.rb, spec/features/admin/stations/admin_stations_index_spec.rb, spec/features/trips/user_sees_dashboard_spec.rb
_x___ Implemented
____ Reviewed
- [] Bug Fix
* description Add user story 30: Admin creates new station feature and spec
closes #30 
=> add admin creates new station feature and spec, user story 30

app/controllers/admin/stations_controller.rb, app/views/admin/stations/_form.html.erb, app/views/admin/stations/edit.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/migrate/20180913151721_change_date_column_stations.rb, db/schema.rb, spec/features/admin/stations/admin_edits_a_station_spec.rb, spec/features/admin/stations/admin_stations_index_spec.rb
x Wrote Tests
x Implemented
____ Reviewed
* description
* Add feature spec for admin editing station
* Add implementation for editing station as admin
* Changes Stations table installation_date column type to date from datetime
closes #31 
https://media.giphy.com/media/ypnDdtNRbjTJ6/giphy.gif
=> Add ability for admin to edit stations

app/controllers/admin/stations_controller.rb, db/seeds.rb, spec/features/admin/stations/admin_edits_a_station_spec.rb, spec/features/admin/stations/admin_stations_index_spec.rb
____ Reviewed
* description
* Fixes small bug with handling dates with new and edit admin station functionality
closes #
https://media.giphy.com/media/1xOQlQxrIX4Jw6lBZI/giphy.gif
=> Fixes small error with dates

app/controllers/admin/stations_controller.rb, app/views/admin/stations/index.html.erb, spec/features/admin/stations/admin_deletes_a_station_spec.rb
x Wrote Tests
x Implemented
____ Reviewed
- [] Bug Fix
* description
* Add ability for admin to delete a station
* Add controller action for destroying a station
closes #32 
https://media.giphy.com/media/xDG1eyoIJBJxC/giphy.gif
=> Add ability for admin to delete a station from station index page

app/controllers/carts_controller.rb, app/models/cart.rb, spec/features/cart/user_checkouts_a_cart_spec.rb, spec/models/cart_spec.rb
x Wrote Tests
x Implemented
____ Reviewed
- [] Bug Fix
* description
* When checkout is clicked and user is logged in, a new order and order accessories are made with order info
closes #100 
https://media.giphy.com/media/unIExoxkdzSE0/giphy.gif
=> Checkout makes new order

app/assets/stylesheets/application.scss, app/views/stations/dashboard.html.erb, app/views/trips/dashboard.html.erb, spec/features/stations/user_sees_stations_dashboard_spec.rb, spec/features/trips/user_sees_dashboard_spec.rb
__x_ Reviewed
- [] Bug Fix
* dashboard styling to stations and index
closes #
=> Dashboards

app/controllers/conditions_controller.rb, app/controllers/stations_controller.rb, app/views/conditions/index.html.erb, app/views/stations/index.html.erb
____ Reviewed
- [] Bug Fix
* description a lil bit o pagination
closes #
=> More pagination

app/controllers/admin/trips_controller.rb, app/views/admin/trips/_form.html.erb, app/views/admin/trips/edit.html.erb, app/views/admin/trips/index.html.erb, app/views/admin/trips/new.html.erb, app/views/trips/show.html.erb, config/routes.rb, spec/features/admin/trips/admin_adds_new_trip_spec.rb, spec/features/admin/trips/admin_deletes_a_trip_spec.rb, spec/features/admin/trips/admin_edits_a_trip_spec.rb, spec/features/admin/trips/admin_views_trip_show_page_spec.rb, spec/features/admin/trips/admin_visits_trip_index_spec.rb
x Wrote Tests
x Implemented
____ Reviewed
- [] Bug Fix
* description
* Add admin ability to create a new trip
* Add admin ability to edit an existing trip
* Add admin ability to delete a trip
* Add edit and delete buttons to trip show page
closes #33, #35, #34, #37, #36 
https://media.giphy.com/media/JuUUmDTJwyahG/giphy.gif
=> Admin trips

db/seeds.rb
____ Reviewed
* description
* Fixes seed file, adds full_name to User creation and full address to Order creation.
closes #
=> Fixes seed file

Gemfile, Gemfile.lock, active_designer/index.html, app/models/condition.rb, db/seeds.rb, spec/factories/conditions.rb, spec/features/conditions/user_sees_conditions_dashboard_spec.rb, spec/models/condition_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
=> Conditions dash

app/views/stations/index.html.erb, app/views/stations/show.html.erb, spec/features/accessories/user_sees_accessory_show_page_spec.rb, spec/features/accessories/user_sees_bike_shop_spec.rb, spec/features/admin/accessories/admin_creates_new_accessory_spec.rb, spec/features/admin/accessories/admin_edits_an_accessory_spec.rb, spec/features/admin/conditions/condition_show_spec.rb, spec/features/admin/conditions/conditions_index_spec.rb
__x_ Reviewed
* fixed views from previous merge. fixed errors
closes #
=> fixed views and errors

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
x Reviewed
- [  ] All Tests are Passing
- [  ] New feature
* description
* Fixes bootstrap implementation with JS in Rails
closes #
- [  ] This broke some stuff
- [  ] This broke everything
- [  ] No Tests have been changed
- [  ] Some Tests have been changed
- [  ] All of the Tests have been changed(Please describe what in the world happened)
- [  ] My code has no unused/commented out code
- [  ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have fully tested my code
https://media.giphy.com/media/oq7qUeVIW3EBy/giphy.gif
=> Drop down debug

app/controllers/admin/conditions_controller.rb, app/controllers/admin/trips_controller.rb, app/controllers/users_controller.rb, app/uploaders/accessory_image_uploader.rb, config/routes.rb, spec/factories/accessories.rb, spec/features/admin/conditions/condition_show_spec.rb, spec/features/admin/conditions/conditions_index_spec.rb, spec/features/admin/stations/admin_edits_a_station_spec.rb, spec/features/admin/trips/admin_adds_new_trip_spec.rb, spec/features/admin/trips/admin_edits_a_trip_spec.rb, spec/features/admin/trips/admin_visits_trip_index_spec.rb, spec/features/users/admin_visits_user_show_page_spec.rb, spec/features/users/authenticate_new_user_spec.rb, spec/features/users/user_authorization_spec.rb
x Wrote Tests
x Reviewed
- [] Bug Fix
* Adjusts some tests for 100% test coverage, added 2 tests missing for 100% coverage
closes #
https://media.giphy.com/media/4DQqW0TezXNRe/giphy.gif
=> Adjusting minor issues with test coverage

app/views/conditions/dashboard.html.erb, app/views/trips/dashboard.html.erb
__x_ Reviewed
* gets second column off of the right margin
closes #
=> aligns dashboard

app/controllers/admin/stations_controller.rb, app/controllers/admin/trips_controller.rb, app/controllers/orders_controller.rb, app/helpers/admin/accessories_helper.rb, app/models/condition.rb, app/models/trip.rb, app/models/user.rb, app/views/conditions/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/models/user_spec.rb
____ Reviewed
- [] Bug Fix
* description: Add first round of basic file cleaning, add validation for password confirmation
closes #
=> add basic file cleaning, add validation for password confirmation

app/views/carts/index.html.erb, spec/features/cart/user_sees_cart_page_spec.rb, spec/features/cart/visitor_adds_to_cart_spec.rb, spec/features/cart/visitor_removes_from_cart_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
=> adds styling to cart index, changes tests, ATP

app/assets/stylesheets/application.scss, app/views/accessories/show.html.erb, app/views/conditions/index.html.erb, app/views/conditions/show.html.erb, app/views/layouts/application.html.erb, app/views/stations/index.html.erb, app/views/stations/show.html.erb, app/views/trips/index.html.erb, app/views/trips/show.html.erb
__x_ Reviewed
* centers buttons
closes #
=> Center buttons

app/controllers/admin/accessories_controller.rb, app/views/accessories/show.html.erb, app/views/admin/accessories/index.html.erb, spec/features/accessories/user_sees_accessory_show_page_spec.rb
___x_ Wrote Tests
____ Reviewed
* description
closes #
=> fixes retire/reactivate button for accessory show, adds tests

app/controllers/admin/stations_controller.rb, app/models/station.rb, app/models/trip.rb, app/views/stations/show.html.erb, config/routes.rb, spec/features/admin/stations/admin_deletes_a_station_spec.rb, spec/features/admin/stations/admin_edits_a_station_spec.rb, spec/features/admin/stations/admin_station_show_spec.rb, spec/features/admin/stations/admin_stations_index_spec.rb, spec/features/users/user_authorization_spec.rb, spec/models/station_spec.rb, spec/models/trip_spec.rb
x Wrote Tests
x Implemented
____ Reviewed
* Add associations for Trip and Stations
* Add dependent destroy associations for Stations
* Removed unnecessary admin station paths
closes #
=> Delete station deletes trips

spec/features/admin/accessories/admin_views_accessory_show_spec.rb, spec/features/users/authenticate_registered_user_spec.rb
____ Reviewed
- [] Bug Fix
* description
closes #
=> Test fixer

app/assets/stylesheets/application.scss, app/controllers/users_controller.rb, app/views/admin/conditions/_form.html.erb, app/views/admin/stations/_form.html.erb, app/views/admin/trips/_form.html.erb, app/views/carts/index.html.erb, app/views/conditions/index.html.erb, app/views/sessions/new.html.erb, app/views/users/edit.html.erb, app/views/users/new.html.erb, spec/features/cart/visitor_adds_to_cart_spec.rb, spec/features/cart/visitor_removes_from_cart_spec.rb
x Implemented
____ Reviewed
- [] Bug Fix
* description
* Add styling to all user input forms
closes #
https://media.giphy.com/media/26BnbmIl6KL1FT9qo/giphy.gif
=> Form styling

app/assets/stylesheets/application.scss, app/controllers/admin/users_controller.rb, app/controllers/conditions_controller.rb, app/controllers/users_controller.rb, spec/features/users/admin_visits_their_show_page_spec.rb, spec/features/users/admin_visits_user_show_page_spec.rb
x Wrote Tests
x Implemented
____ Reviewed
* description
* Add styling to flash messages
* Fixes admin viewing a user page
closes #
https://media.giphy.com/media/ueDcEbafnr4di/giphy.gif
=> Adds more styling

app/views/accessories/show.html.erb
____ Reviewed
* description Fix Retire button on accessory show page
closes #
=> fix retire button on accessory show page

app/views/accessories/show.html.erb, app/views/conditions/show.html.erb, app/views/stations/show.html.erb, app/views/trips/show.html.erb
____ Reviewed
- [] Bug Fix
* description
closes #
=> Show pages styling

app/views/admin/accessories/index.html.erb, spec/features/admin/accessories/admin_views_accessory_index_spec.rb, spec/features/admin/accessories/admin_views_accessory_show_spec.rb, spec/features/admin/orders/admin_visits_admin_dashboard_orders_spec.rb, spec/features/users/user_sees_their_dashboard_spec.rb
x Implemented
____ Reviewed
* Fixes a couple of tests broken due to styling
closes #
https://media.giphy.com/media/10bHcDcPM925ry/giphy.gif
=> fixed a couple tests that were broken due to styling
